name: CI/CD

on:
  schedule:
    - cron: "1-59 * * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Run the Node.js script
        run: node ./index.js

      - name: Commit changes and push back to repository
        run: |
          git config --global user.name "leanhvu5501412"
          git config --global user.email "leanhvu550@gmail.com"
          git add .
          git commit -m "Update file content $(date -R)"
          git push

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.token }}
          publish_dir: ./
