name: CI/CD

on:
  schedule:
    - cron: "1-59 * * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        env:
          token: ${{ secrets.token }}
        run: node index.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Update file content $(date -R)"
          git push
